Flatten the numpy array to give scalar delta_rf value
By flattening this array, the np.dot product returns a scaler
rather than a numpy array with one number in it. This caused issues when
setting a softioc record. Previously softioc would convert this, but now
it gives this error:

Traceback (most recent call last):
  File "/workspaces/dls_slow_feedbacks/src/dls_slow_feedbacks/rffb_server.py", line 64, in run
    self.apply_correction()
  File "/workspaces/dls_slow_feedbacks/src/dls_slow_feedbacks/rffb_server.py", line 108, in apply_correction
    self.delta_pv.set(np.array([5.0]))
  File "/cache/venv-for/scratch/zrv91478/vscode/dls_slow_feedbacks/lib/python3.11/site-packages/softioc/device.py", line 148, in set
    value = self._value_to_epics(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cache/venv-for/scratch/zrv91478/vscode/dls_slow_feedbacks/lib/python3.11/site-packages/softioc/device.py", line 65, in _value_to_epics
    return self._ctype_(value)
           ^^^^^^^^^^^^^^^^^^^
TypeError: only 0-dimensional arrays can be converted to Python scalars